routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::group([

        'middleware'    => ['auth','userRole','checkRole:admin,commite'],

        // 'middleware'    => 'auth',
    
      ], function () {

        Route::get('admin', function () {
            return redirect('/admin/list-tim');
        });

        Route::resource('admin/list-tim', 'Admin_ListTimController');
        Route::resource('admin/submission', 'Admin_SubmissionController');
        Route::resource('admin/admin-payment','Admin_PaymentController');

    });
});

Route::name('admin.')->group(function () {
    Route::group([

        'middleware'    => ['auth','userRole','checkRole:admin'],

        // 'middleware'    => 'auth',
    
      ], function () {


        Route::resource('admin/commite', 'CreateCommite');
        Route::resource('admin/delete', 'DeleteFile');

    });
});

routes/web.php
<?php
// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

Route::resource('/', 'LandingPageController');
Route::post('/register-team', 'LandingPageController@registerteam')->name('register-team');


require('admin.php');
require('team.php');

app/Models/Team.php
<?php

namespace App\Models;

use App\MasterModel;
use App\User;
use App\Models\Competitions;

class Team extends MasterModel
{
    protected $table= 'teams';
    protected $gruarderd= ['id'];

    protected $fillable = [
        'name',
        'username',
        'password',
        'institution',
        'status',
        'competition_id',
    ];
    // protected $primaryKey = 'id';
    // public $incrementing = false;
    public function competitions()
    {
        return $this->belongsTo(Competitions::class, 'competition_id', 'id');
    }

    public function participants()
    {
        return $this->hasMany(Participants::class);
    }

    public function payment()
    {
        return $this->hasMany(Payment::class);
    }

    public function submission_team()
    {
        return $this->hasMany(Submission_team::class);
    }

    public function user()
    {
        return $this->hasOne(User::class);
    }
}

app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use Auth;
use File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Models\Team;
use App\Models\Participants;
use App\User;
use App\Models\Submission_team;
use App\Models\Submission;
use Illuminate\Support\Facades\Session;

class TeamController extends Controller
{
    public function index()
    {
        $teams = Auth::user()->username;
        // dd($teams);
        $team_ahh = Team::join('competitions', 'teams.competition_id', '=', 'competitions.id')->where('username', $teams)->get();
        $participants = Participants::where('team_id', $teams)->orderBy('id', 'asc')->get();
        $pc = $participants->count();
        // dd($pc);

        return view('team.new.team', ['participants' => $participants], ['teamku' => $team_ahh])->with('pc', $pc);
    }

    public function store(Request $request)
    {

        request()->validate([
            'identity_card' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        $teams = Auth::user()->team_id;

        $identity_card = $request->file('identity_card');
        $file_name = Auth::user()->team_id . '_' . $request->name . '.' . $identity_card->getClientOriginalExtension();
        $identity_card->move('uploads/identity_card/', $file_name);

        $participant = new Participants;
        $participant->team_id = Auth::user()->team_id;
        $participant->status = 'Anggota';
        $participant->identity_card = $file_name;
        $participant->name = $request->name;
        $participant->birth_date = $request->birth_date;
        $participant->email = $request->email;
        $participant->phone = $request->phone;
        $participant->save();

        return redirect('team');
    }

    public function update($id, Request $request)
    {

        $file_name = Participants::select('identity_card')->where('id', $id)->first()->identity_card;
        File::delete('uploads/identity_card/' . $file_name);

        $file = $request->identity_card;
        $filename = Auth::user()->team_id . '_' . $request->name . '_update' . '.' . $file->getClientOriginalExtension();
        $destinationPath = 'uploads/identity_card/';

        File::delete('uploads/identity_card/' . $filename);
        $file->move($destinationPath, $filename);

        $participants = Participants::find($id);
        // dd($participants);
        $participants->identity_card = $filename;
        $participants->name = $request->name;
        $participants->birth_date = $request->birth_date;
        $participants->email = $request->email;
        $participants->phone = $request->phone;
        $participants->save();

        return redirect('team')->with('success', 'Data telah tersimpan');
    }

    public function destroy($id)
    {
        $tm = Participants::findOrFail($id);
        $file_name = Participants::select('identity_card')->where('id', $id)->first()->identity_card;

        File::delete('uploads/identity_card/' . $file_name);
        $tm->delete();
        return redirect('team')->with(['message' => 'Successfully deleted!!']);
    }

    public function video()
    {
        $team_id = Auth::user()->team_id;
        $competition_id = Team::select('competition_id')->where('id', $team_id)->first()->competition_id;

        $submission_id = Submission::select('id')->where('name', 'Pengumpulan Link Video')
            ->where('competition_id', $competition_id)
            ->first()->id;


        $submission_id_before = Submission::select('id')->where('name', 'Pengumpulan Proposal')
            ->where('competition_id', $competition_id)
            ->first()->id;
        $submission_team = Submission_team::all()->where('team_id', Auth::user()->team_id)
            ->where('submission_id', $submission_id)->first();
        $submission_teams_before = Submission_team::where('team_id', Auth::user()->team_id)
            ->where('submission_id',  $submission_id_before);
        $submission_team_before =  $submission_teams_before->first();
        
        $id = str_replace('/', '', parse_url($submission_team->document, PHP_URL_PATH));

        return view('team.new.video', [
            'submission_team' => $submission_team,
            'submission_team_before' => $submission_team_before,
            'done' => $submission_team,
            'id' => $id,
        ]);
    }

    public function videostore(Request $request)
    {
        $team_id = Auth::user()->team_id;
        $competition_id = Team::select('competition_id')->where('id', $team_id)->first()->competition_id;
        $url = $request->get('link');
        $submission_id = Submission::select('id')->where('name', 'Pengumpulan Link Video')
            ->where('competition_id', $competition_id)
            ->first()->id;
        $domain = parse_url($url, PHP_URL_HOST);
        if ($domain == 'www.youtube.com' || $domain == 'youtube.com') {
            $submission = new Submission_team;
            $submission->submission_id = $submission_id;
            $submission->team_id = $team_id;
            $submission->document = $url;
            $submission->status = 'On Progress';
            $submission->save();
            return redirect('team/video')->with('success', 'Data telah terkirim');
        } elseif ($domain == 'youtu.be') {
            $submission = new Submission_team;
            $submission->submission_id = $submission_id;
            $submission->team_id = $team_id;
            $submission->document = $url;
            $submission->status = 'On Progress';
            $submission->save();
            return redirect('team/video')->with('success', 'Data telah terkirim');
        } else {
            return redirect('team/video')->with('error', 'Format link salah');
        }
    }

    public function setting()
    {
        return view('team.new.setting');
    }


    public function settingstore(Request $request)
    {

        $pass = User::select('password')->where('team_id', Auth::user()->team_id)->first()->password;

        if (Hash::check($request->password_lama, $pass)) {

            User::where('team_id', Auth::user()->team_id)->update(array('password' => Hash::make($request->password)));
            Team::where('id', Auth::user()->team_id)->update(array('password' => Hash::make($request->password)));
            Session::flash('sukses', 'Selamat password anda telah diubah');
        } else {
            Session::flash('gagal', 'Maaf password yang anda masukan salah');
        }

        return redirect('team/setting')->with('success', 'Data telah terkirim');
    }
}

resources/views/team/new/payment.blade.php
@extends('dashboard-template')
@section('content')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Pembayaran</li>
</ol>


<div class="alert alert-secondary" role="alert">
    <h4 class="alert-heading">HI, {{Auth::user()->name}}</h4>
    <p>Silahkan melakukan pembayaran pendaftaran ke :</p>
    <hr>
    <h5 class="alert-heading">
        Jenis Bank : Mandiri <br>
        No. Rekening : 141-00-1778933 a.n Ayu Bhuana <br>
        Nominal : Rp 150,000
    </h5>
    <hr>
    <h4 class="alert-heading mb-0">INGAT! Nominal harus sesuai dengan yang disebutkan diatas. Jika tidak, maka data tidak akan diproses.</h4>
    <p class="mb-0">
        Setelah melakukan pembayaran, upload bukti pembayaran dan mohon menunggu verifikasi oleh panitia INTEGER maksimal 2 x 24 jam.
        <br> Contact Person : Imam Mahudi - <span><a target="_blank" href="https://wa.me/6285748966083">085748966083 (WA)</a></span>
    </p>
</div>


<div class="card">
    <div class="card-body">
        @if(!isset($payment->id))
        <form action="{{ route('team.payments.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="pembayaran">Upload Bukti Pembayaran</label>
                        <input type="file" class="form-control-file" name="evidence">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control form-control-alternative" rows="3" name="description" placeholder="Keterangan"></textarea>
                    </div>
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
        @endif

        @if(isset($payment))
        <div class="row">
            <div class="col-4">
                <b>Bukti</b><br><br>
                <img src="/uploads/payment/{{ $payment->evidence }}" alt="" srcset="" width="100%">
            </div>
            <div class="col-4">
                <b>Status Pembayaran</b><br><br>
                @if($payment->team->status == 'Belum Terverifikasi')
                <button type="button" class="btn btn-danger btn-sm">Pending</button>
                @elseif($payment->team->status == 'Sudah')
                <button type="button" class="btn btn-success btn-sm">Success</button>
                @endif
            </div>
            <div class="col-4">
                <b>Waktu Submit</b><br><br>
                {{ $payment->created_at }}
            </div>
        </div>
        @endif

    </div>
</div>

@stop

resources/views/team/new/proposal.blade.php
@extends('dashboard-template')
@section('content')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Upload Proposal</li>
</ol>


@if(isset($done->id))
@if($proposal->status == 'Lolos')
<div class="alert alert-success">
    <strong>Selamat!</strong> Tim anda lolos, dan melanjutkan ke tahap berikutnya
</div>
@elseif($proposal->status == 'Tidak Lolos')
<div class="alert alert-danger">
    <strong>Maaf!</strong> Tim anda tidak lolos, tetap semangat dan coba lagi di lain kesempatan
</div>
@else
<div class="alert alert-success">
    <strong>Sukses!</strong> Terimakasih atas partisipasi anda. Silahkan menunggu pengumuman selanjutnya
</div>
@endif
@endif

@if($payment->status == 'Belum Terverifikasi')
<div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">HI, {{Auth::user()->name}}</h4>
    <p>Silahkan melakukan pembayaran terlebih dahulu dan tunggu approve dari panitia sebelum melakukan upload proposal. terimakasih :)</p>
</div>
@endif


<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-xl-12" style="">
                @if($payment->status == "Sudah" && !isset($done->id))
                <button class="btn btn-icon btn-3 btn-success" data-toggle="modal" data-target="#proposal" type="button">
                    <i class="fa fa-plus" aria-hidden="true"> Upload Proposal</i>
                </button>
                @endif
            </div>
            <div class="col-xl-12" style="margin-top: 1em;">
                @if (count($errors) > 0)
                <div class="alert alert-danger">
                    Upload Validation Error<br><br>
                    <ul>
                        @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
                @endif
                 @if($proposal == null)
                <div class="alert alert-danger" role="alert" style="margin-top: 1em;">
                    <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
                    <br>
                    Belum ada proposal yang diupload <br>
                    Proposal di upload wajib dalam bentuk file <b>.pdf</b>
                </div>
                @else
                <div class="row">
                    <div class="col-6">
                        <b>Proposal</b><br><br>
                        <a href="{{ asset('uploads/proposal/'.$proposal->document) }}">{{ $proposal->document }}</a>
                    </div>
                    <div class="col-6">
                        <b>Waktu Submit</b><br><br>
                        {{ $proposal->updated_at }}
                    </div>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>

<!-- modal upload proposal-->
<div class="modal fade" id="proposal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Upload Proposal</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="post" action="{{ route('team.submission.store') }}" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <input type="file" class="form-control-file" name="document">
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Upload</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- modal upload proposal-->

@stop

resources/views/team/new/setting.blade.php
@extends('dashboard-template')
@section('content')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Setting</li>
</ol>

@if ($message = Session::get('gagal'))
    <div class="alert alert-danger alert-block">
        <button type="button" class="close" data-dismiss="alert">×</button> 
        <strong>{{ $message }}</strong>
    </div>
@endif

@if ($message = Session::get('sukses'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

<div class="card">
    <div class="card-body">
        <form action="{{ route('team.setting.store')}}" method="POST">
            {{csrf_field()}}
            {{ method_field('PUT')}}
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Password lama</label>
                        <input type="password" name="password_lama" id="password" class="form-control form-control-alternative" placeholder="Password" required>
                    </div>
                    <div class="form-group">
                        <label class="form-control-label" for="input-first-name">Password Baru</label>
                        <input type="password" name="password" id="password" class="form-control form-control-alternative" placeholder="Password" required>
                    </div>
                </div>
                <div class="col-md-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

@stop

resources/views/team/new/sidebar.blade.php
<li class="nav-item {{ request()->is('team') ? 'active' : '' }}">
    <a class="nav-link " href="/team">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span>
    </a>
</li>
<li class="nav-item {{ request()->is('team/payments*') ? 'active' : '' }}">
    <a class="nav-link " href="/team/payments">
        <i class="fas fa-fw fa-dollar-sign"></i>
        <span>Pembayaran</span>
    </a>
</li>
<li class="nav-item {{ request()->is('team/submission*') ? 'active' : '' }}">
    <a class="nav-link" href="/team/submission">
        <i class="fas fa-fw fa-file-word"></i>
        <span>Upload Proposal</span>
    </a>
</li>
<li class="nav-item {{ request()->is('team/video*') ? 'active' : '' }}">
    <a class="nav-link" href="/team/video">
        <i class="fas fa-fw fa-file-video"></i>
        <span>Upload Video</span>
    </a>
</li>
<li class="nav-item {{ request()->is('team/setting*') ? 'active' : '' }}">
    <a class="nav-link" href="/team/setting">
        <i class="fas fa-fw fa-cogs"></i>
        <span>Setting</span>
    </a>
</li>

resources/views/team/new/team.blade.php
@extends('dashboard-template')
@section('content')
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Tim</li>
</ol>

<!-- Page Content -->
<div class="card">
    <div class="card-body">
        <div class="row">
            @foreach ($teamku as $y)
            <div class="col-xl-6">
                <h3><b>{{ Auth::user()->name }}</b></h3>
                <h4><small>{{ $y->institution }}</small></h4>
            </div>
            <div class="col-xl-6 mt-3">
                Kategori
                <h5><b>{{ $y->name }}</b></h5>
            </div>
            <div class="col-xl-12 mt-3">
                @if($y->status == "Sudah")
                <div class="alert alert-success">
                    <b>Terverifikasi</b>
                </div>
                @else
                <div class="alert alert-danger">
                    <b>Belum Terverifikasi</b>
                </div>
                @endif
            </div>
            @endforeach
        </div>
    </div>
</div>

@if($pc < 3) <div style="margin-top: 1em;">
    <button class="btn btn-icon btn-sm btn-success" data-toggle="modal" data-target="#tambah-anggota" type="button">
        <i class="fa fa-plus" aria-hidden="true"><span> Tambah Anggota</span></i>
    </button>
    </div>
    @else
    <div class="alert alert-info" role="alert" style="margin-top: 1em;">
    <i class="fa fa-info-circle" aria-hidden="true">   Anggota Team Maximal 3 Orang</i>
    </div>
    @endif

    @if (count($errors) > 0)
    <div class="alert alert-danger" style="margin-top: 1em;">
        Error<br><br>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="card mt-4">
        <h4 class="card-header">List Anggota</h4>
        <div class="card-body">
            <div class="table-responsive">
                <table id="table_team" class="table table-striped table-bordered second" style="width:100%">
                    <thead>
                        <tr style="text-align: center">
                            <th>Kartu Identitas</th>
                            <th style="width: 200px;">Nama</th>
                            <th>Email</th>
                            <th>No. Telepon</th>
                            <th>Status</th>
                            <th style="width: 150px;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($participants as $x)
                        <tr style="text-align: center">
                            <td><img src="{{ asset('uploads/identity_card/'.$x->identity_card) }}" style="width:35%;" alt="identitiy_card"></td>
                            <td>{{ $x->name }}</td>
                            <td>{{ $x->email }}</td>
                            <td>{{ $x->phone }}</td>
                            <td>{{ $x->status }}</td>
                            <td>
                                @if( $x->status=="Ketua" )
                                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#update-peserta{{ $x->id }}" style="float: left;">
                                    <span class="btn-inner--icon"><i class="fas fa-edit"></i></span>
                                </button>
                                @else
                                <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#update-peserta{{ $x->id }}" style="float: left; margin-right: 1em;">
                                    <span class="btn-inner--icon"><i class="fas fa-edit"></i></span>
                                </button>
                                <form action="{{ route('team.participants.destroy', $x->id) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" style="float: left;"><span class="btn-inner--icon"><i class="fas fa-trash"></i></span></button>
                                </form>
                                @endif
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <!-- modal insert peserta -->
    <div class="modal fade" id="tambah-anggota" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Tambah Anggota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" name="list_anggota" enctype="multipart/form-data" action="{{ route('team.participants.store')}}">
                        {{csrf_field()}}
                        <input type="hidden" value="{{ (Auth::user()->team_id) }}" name="team">
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-id-card" aria-hidden="true"></i></span>
                                </div>
                                <input class="form-control" placeholder="Kartu Identitas" name="identity_card" type="file" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
                                </div>
                                <input class="form-control" placeholder="Nama Lengkap" type="text" name="name" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-birthday-cake"></i></span>
                                </div>
                                <input class="form-control" placeholder="Tanggal Lahir" type="date" name="birth_date" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-envelope-open"></i></span>
                                </div>
                                <input class="form-control" placeholder="Email" type="email" name="email" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-phone-square"></i></span>
                                </div>
                                <input class="form-control" placeholder="Phone" type="number" name="phone" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- modal insert peserta -->


    @foreach ($participants as $x)
    <!-- modal update peserta -->
    <div class="modal fade" id="update-peserta{{ $x->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Update Anggota</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="POST" name="list_anggota" enctype="multipart/form-data" action="{{ route('team.participants.update',[$x->id])}}">
                        {{csrf_field()}}
                        {{ method_field('PUT')}}
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-id-card"></i></span>
                                </div>
                                <input class="form-control" type="hidden" name="id">
                                <input class="form-control" placeholder="Kartu Identitas" name="identity_card" type="file" value="{{ $x->identity_card }}" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-user-circle"></i></span>
                                </div>
                                <input class="form-control" placeholder="Nama Lengkap" type="text" name="name" value="{{ $x->name }}" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-birthday-cake"></i></span>
                                </div>
                                <input class="form-control" placeholder="Tanggal Lahir" type="date" name="birth_date" value="{{ $x->birth_date }}" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-envelope-open"></i></span>
                                </div>
                                <input class="form-control" placeholder="Email" type="email" name="email" value="{{ $x->email }}" required>
                            </div>
                        </div>
                        <div class="form-group mb-3">
                            <div class="input-group input-group-alternative">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fa fa-phone-square"></i></span>
                                </div>
                                <input class="form-control" placeholder="Phone" type="number" name="phone" value="{{ $x->phone }}" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- modal update peserta -->
    @endforeach




    @stop