routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::name('admin.')->group(function () {
    Route::group([

        'middleware'    => ['auth','userRole','checkRole:admin,commite'],

        // 'middleware'    => 'auth',
    
      ], function () {

        Route::get('admin', function () {
            return redirect('/admin/list-tim');
        });

        Route::resource('admin/list-tim', 'Admin_ListTimController');
        Route::resource('admin/submission', 'Admin_SubmissionController');
        Route::resource('admin/admin-payment','Admin_PaymentController');

    });
});

Route::name('admin.')->group(function () {
    Route::group([

        'middleware'    => ['auth','userRole','checkRole:admin'],

        // 'middleware'    => 'auth',
    
      ], function () {


        Route::resource('admin/commite', 'CreateCommite');
        Route::resource('admin/delete', 'DeleteFile');

    });
});

routes/web.php
<?php
// use Illuminate\Routing\Route;
use Illuminate\Support\Facades\Route;

Auth::routes(['register' => false]);

Route::resource('/', 'LandingPageController');
Route::post('/register-team', 'LandingPageController@registerteam')->name('register-team');


require('admin.php');
require('team.php');

resources/views/admin/new/admin-detail-tim.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin/list-tim">List Team</a>
    </li>
    <li class="breadcrumb-item active">Detail Tim</li>
</ol>

<div class="card w-75">
    <div class="card-body">
        <div class="row">
            <div class="col-xl-6">
                <h3><b>{{ $team->name }}</b></h3>
                <span>{{ $team->institution }}</span>
            </div>
            <div class="col-xl-6 mt-3">
                Kategori
                <h5><b>{{$team->competitions->name}}</b></h5>
            </div>
        </div>
    </div>
</div>

<div class="row">
    @foreach($participant1 as $key)
    <div class="col-lg-6 mt-2">
        <div class="card">
            <div class="card-header" style="padding-bottom:1px;">
                <h5 class="card-title" style="margin-bottom:1px;">Ketua Tim</h5>
            </div>
            <div class="card-body p-4" style="padding-bottom:1em;">
                <div class="row">
                    <div class="col-lg-4">
                        <h5>Nama</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->name }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Tanggal Lahir</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->birth_date }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Email</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->email }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Kartu Identitas</h5>
                    </div>
                    <div class="col-lg-12">
                        <img src="{{ asset('uploads/identity_card/'.$key->identity_card) }}" alt="" srcset="" width="50%">
                    </div>

                </div>
            </div>
        </div>
    </div>
    @endforeach

    @foreach($participant2 as $key)
    <div class="col-lg-6 mt-2">
        <div class="card">
            <div class="card-header" style="padding-bottom:1px;">
                <h5 class="card-title" style="margin-bottom:1px;">Anggota</h5>
            </div>
            <div class="card-body p-4" style="padding-bottom:1em;">
                <div class="row">
                    <div class="col-lg-4">
                        <h5>Nama</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->name }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Tanggal Lahir</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->birth_date }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Email</h5>
                    </div>
                    <div class="col-lg-8">
                        : {{ $key->email }}
                    </div>

                    <div class="col-lg-4">
                        <h5>Kartu Identitas</h5>
                    </div>
                    <div class="col-lg-12">
                        <img src="{{ asset('uploads/identity_card/'.$key->identity_card) }}" alt="" srcset="" width="50%">
                    </div>

                </div>
            </div>
        </div>
    </div>
    @endforeach
</div>
<div class="mt-5">
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.list-tim.destroy', $team->username) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('DELETE') }}
                <button class="btn btn-lg btn-danger" type="submit" onclick="return confirm('Yakin ingin menghapus data?')" style="float: left;"><span class="btn-inner--icon"><i class="fas fa-trash"></i> Hapus Tim</span></button>
            </form>
        </div>
    </div>
</div>


@stop

resources/views/admin/new/admin-list-tim.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">List Team</li>
</ol>


<div class="card-body">
    <div class="table-responsive">
        <table id="list_anggota" class="table table-striped table-bordered second" style="width:100%">
            <thead>
                <tr>
                    <th>Nama Tim</th>
                    <th>Institusi</th>
                    <th>Kategori Lomba</th>
                    <th>Status Bayar</th>
                    <th>Detail</th>
                </tr>
            </thead>
            <tbody>
                @foreach($teams as $key)
                <tr>
                    <td>{{ $key->name }}</td>
                    <td>{{ $key->institution }}</td>
                    <td>{{ $key->competitions->name }}</td>
                    <td>{{ $key->status }}</td>
                    <td>
                        <a class="btn btn-primary btn-sm" href="/admin/list-tim/{{ $key->username }}">Detail</a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@stop

resources/views/admin/new/admin-payment-detail.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="/admin/payment">Pembayaran</a>
    </li>
    <li class="breadcrumb-item active">Detail</li>
</ol>

<div class="card w-75">
    <div class="card-body">
        <div class="row">
            <div class="col-xl-6">
                <h3><b>{{ $pay->team->name }}</b></h3>
                <span>{{ $pay->team->institution }}</span>
            </div>
            <div class="col-xl-6 mt-3">
                Kategori
                <h5><b>{{$pay->team->competitions->name}}</b></h5>
            </div>
        </div>
    </div>
</div>

<div class="card">
    <div class="card-body" style="padding-bottom:1em;">
        <div class="box-body table-responsive no-padding">
            <form action="{{ route('admin.admin-payment.update',[$pay->team_id]) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT')}}
                <div class="form-group">
                    <label for="nama">Evidence :</label>
                    <img width="250px" src="{{ asset('uploads/payment/'.$pay->evidence) }}">

                </div>
                <div class="form-group">
                    <label for="nama">Description :</label>
                    <input type="text" disabled class="form-control" id="usr" name="evidence" value="{{ $pay->description }}">
                </div>
                <div class="form-group">
                    <label for="status">Status:</label>
                    <input type="text" class="form-control" id="status" name="status1" value="{{ $pay->team->status }}">
                    <input type="text" class="form-control" hidden id="status" name="status" value="Sudah">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-md btn-primary">Approve</button>
                    <button type="reset" class="btn btn-md btn-danger">Cancel</button>
                </div>
            </form>
        </div>

    </div>
</div>

@stop

resources/views/admin/new/admin-payment.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Pembayaran</li>
</ol>

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table id="list_anggota" class="table table-striped table-bordered second" style="width:100%">
                <thead>
                    <tr>
                        <th>Nama Tim</th>
                        <th>Institution</th>
                        <th>Evidence</th>
                        <th>Description</th>
                        <th>Status</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                @foreach ($payment as $pay)
                <tbody>
                    <tr>
                        <td>
                            @if(isset($pay->team->name))
                            {{ $pay->team->name }}
                            @endif
                        </td>
                        <td>
                            @if(isset($pay->team->institution))
                            {{ $pay->team->institution }}
                            @endif
                        </td>
                        <td>{{ $pay->evidence }}</td>
                        <td>{{ $pay->description }}</td>
                        <td>
                            @if(isset($pay->team->status))
                            {{ $pay->team->status }}</td>
                            @endif
                        <td>
                            @if(isset($pay->team->status))
                                @if($pay->team->status == 'Belum Terverifikasi')
                                <a class="btn btn-primary btn-sm" href="{{route('admin.admin-payment.edit',[$pay->id])}}">Detail</a>
                                @else
                                <button type="button" class="btn btn-success btn-sm">Success</button>
                                @endif
                            @endif
                        </td>
                    </tr>
                </tbody>
                @endforeach
            </table>
        </div>
    </div>
</div>

@stop

resources/views/admin/new/admin-submission-detail.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Submission</li>
</ol>

<div class="row">
    <div class="col-xl-12 col-md-12 col-sm-12">
        <div class="nav-wrapper">
            <ul class="nav nav-pills nav-fill flex-column flex-md-row" id="tabs-icons-text" role="tablist">
                @foreach($submissions as $key)
                <li class="nav-item">
                    <a class="nav-link mb-sm-3 mb-md-0" id="{{ $key->id }}-tab" data-toggle="tab" href="#{{ $key->id }}-text" role="tab" aria-controls="tabs-icons-text-1" aria-selected="true">{{ $key->name }}</a>
                </li>
                @endforeach
            </ul>
        </div>

        <div class="card shadow">
            <div class="card-body">
                <div class="tab-content" id="myTabContent">
                    @foreach($submissions as $key)
                    <div class="tab-pane fade show" id="{{ $key->id }}-text" role="tabpanel" aria-labelledby="{{ $key->id }}-tab">
                        <div class="table-responsive">
                            <table id="" class="table table-striped table-bordered second" style="width:100%">
                                <thead>
                                    <tr>
                                        <th>Nama Tim</th>
                                        <th>Institusi</th>
                                        <th>Tanggal Upload</th>
                                        <th>Terakhir update</th>
                                        <th>Status</th>
                                        <th>Download</th>
                                        <th>lolos opo ora</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($submissionsTeams as $key_1)
                                    @if($key->id == $key_1->submission_id)
                                    <tr>
                                        <td>{{ $key_1->team->name }}</td>
                                        <td>{{ $key_1->team->institution }}</td>
                                        <td>{{ $key_1->created_at }}</td>
                                        <td>{{ $key_1->updated_at }}</td>
                                        <td>{{ $key_1->status }}</td>
                                        <td>
                                            <a href="{{ asset('uploads/proposal/' . $key_1->document) }}" target="_blank" class="btn btn-warning"><i class="cloud-download-95"></i>Download</a>
                                            <br>
                                            <a href="{{ $key->document }}">{{ $key_1->document }}</a>
                                        </td>
                                        <td>
                                            <form action="{{ route('admin.submission.update', [$key_1->id] ) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}
                                                <input type="hidden" value="{{ $key_1->submission_id }}" name="submission_id">
                                                @if($key_1->status == 'Lolos')
                                                <button type="submit" class="btn btn-danger">Batalkan Lolos</button>
                                                @else
                                                <button type="submit" class="btn btn-success">Loloskan</button>
                                                @endif
                                            </form>
                                        </td>
                                    </tr>
                                    @endif
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>
</div>

@stop

resources/views/admin/new/admin-submission.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">Submission</li>
</ol>

<div class="row">
    @foreach($competitions as $key)
    <div class="col-xl-6 col-md-12 col-sm-12">
        <div class="card">
            <div class="card-header bg-white border-0">
                <div class="row align-items-center">
                    <div class="col-8">
                        <h3 class="mb-0">{{ $key->name }}</h3>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>Klik detail untuk lihat submission</p>
                <a href="/admin/submission/{{ $key->id }}" class="btn btn-primary">Detail</a>
            </div>
        </div>
    </div>
    @endforeach
</div>

@stop 

resources/views/admin/new/commite.blade.php
@extends('dashboard-template')
@section('content')

<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item active">List User</li>
</ol>

<button class="btn btn-icon btn-sm btn-success" data-toggle="modal" data-target="#add-user" type="button">
    <span class="btn-inner--icon"><i class="ni ni-fat-add"></i></span>
    <span class="btn-inner--text">Tambah User</span>
</button>

<div class="card">
    <div class="card-body">
        <div class="table-responsive">
            <table id="list_anggota" class="table table-striped table-bordered second" style="width:100%">
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>Username</th>
                        <th>Role</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $key)
                    <tr>
                        <td>{{ $key->name }}</td>
                        <td>{{ $key->username }}</td>
                        <td>{{ $key->role }}</td>
                        <td>
                            <div class="d-flex">
                                <button data-toggle="modal" data-target="#edit-user-{{ $key->id }}" class="btn btn-sm btn-primary">Edit</button>

                                @if($key->role != 'admin')
                                <form action="{{ route('admin.commite.destroy', $key->id) }}" method="post">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-sm btn-danger" type="submit" onclick="return confirm('Yakin nih mau dihapus?')">Hapus</button>
                                </form>
                                @endif
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="modal fade" id="add-user" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Tambah User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('admin.commite.store') }}" method="POST">
                    {{csrf_field()}}
                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input class="form-control" placeholder="Nama Lengkap" type="text" name="name" value="">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input class="form-control" placeholder="Username" type="text" name="username" value="">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input class="form-control" placeholder="Password" type="password" name="password" value="">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-folder"></i></span>
                            </div>
                            <select name="role" class="form-control" id="">
                                <option value="commite">Cuma Panitia</option>
                                <option value="admin">Admin Cuy</option>
                            </select>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@foreach($users as $key)
<div class="modal fade" id="edit-user-{{ $key->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{ route('admin.commite.update', $key->id) }}" method="POST">
                    {{csrf_field()}}
                    <input name="_method" type="hidden" value="PUT">
                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input class="form-control" placeholder="Nama Lengkap" type="text" name="name" value="{{ $key->name }}">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-user"></i></span>
                            </div>
                            <input class="form-control" placeholder="Username" type="text" name="username" value="{{ $key->username }}">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-key"></i></span>
                            </div>
                            <input class="form-control" placeholder="Password" type="password" name="password" value="">
                        </div>
                    </div>

                    <div class="form-group mb-3">
                        <div class="input-group input-group-alternative">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="fas fa-folder"></i></span>
                            </div>
                            <select name="role" class="form-control" id="">
                                <option value="commite">Cuma Panitia</option>
                                <option value="admin">Admin Cuy</option>
                            </select>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>      
@endforeach
@stop

resources/views/admin/new/sidebar.blade.php
<li class="nav-item {{ request()->is('admin/list-tim*') ? 'active' : '' }}">
    <a class="nav-link " href="/admin/list-tim">
        <i class="fas fa-fw fa-users"></i>
        <span>List Tim</span>
    </a>
</li>
<li class="nav-item {{ request()->is('admin/admin-payment*') ? 'active' : '' }}">
    <a class="nav-link " href="/admin/admin-payment">
        <i class="fas fa-fw fa-dollar-sign"></i>
        <span>Pembayaran</span>
    </a>
</li>
<li class="nav-item {{ request()->is('admin/submission*') ? 'active' : '' }}">
    <a class="nav-link" href="/admin/submission">
        <i class="fas fa-fw fa-file-word"></i>
        <span>Submission</span>
    </a>
</li>
<li class="nav-item {{ request()->is('admin/commite*') ? 'active' : '' }}">
    <a class="nav-link" href="/admin/commite">
        <i class="fas fa-fw fa-user"></i>
        <span>User</span>
    </a>
</li>